#!/bin/bash 
for (( i=1; i<66; i++ )) 
  do 
    h=`echo  2^"$i" |bc -l`;
    echo -e -n $i "  " '\t' 
    echo  $h  |tr -d -c [0-9] |rev |sed -e 's/\([0-9][0-9][0-9]\)/\1,/g' |rev | sed 's/^,//';
  done
exit 0
